language: node_js
node_js:
- '5.10'
branches:
  only:
  - master
before_script: bash ./bin/prepare.sh
script:
- npm test
after_success: bash ./bin/deploy.sh
env:
  global:
  - GIT_USER: Travis CI
  - GIT_EMAIL: miya+github.com@wpist.me
  - GH_REF: github.com/madefor/postal-code-api.git
  - secure: Aa5SYwcvFiYS4sJjXFZsmUlkUlRz4VlI7ikRp/4X9T0jn71/pCCWgAVoTT8KT9NTCy7RaG1nm2oZpfi9OSK5lM5m/0CwVZs5RHX4UXd7eaZEaB/M9Caf+8nDa/zb+4vyeEviy8G5CCJUpmRL+JuL1zE+hWmoncMo9ocWzCoVHJvdJ69jHS6T+4jJ7sCLtLSmDea+GfZxeYlPkxxlucnncwwpx2Yd74a31uTCMCn53M/7nd+gS0RT4GWCuiUzpcFFsoID5PZB6slLGYlOLQti0P0JeYDYq78qhEhmDC3IeJsmhXifBu9INz+QLhRP1mFB/eNIUcVMJd+zNnZNLNDq0duyk6SoHQcrZaIGsueZLyVNJg6TnJkguHUGuu/0yRrLfkeJ2yJQvTMczGdLIjHNDp1pmhHi5KTl8blpdnbnmVaQKXYshNfhF02FrHFPXyVe10M2U16tPldES6w5Ck+CvS6L/Ky3C3B0x4wAWK3N34isrM0q+aPbbofuBNXA2baq1LPHAAKDcMBktUuprvraj8NosNlJyX+nVjRIKbd9rPWOarZpWO/MhI/g4kqpb+LycuWfcQBnNp+9RcaeVvnU/2FAFtQAAOJvZvNDWSF7HDol78d0EX6anCj1pRW1a3x2kzLxLiTqaYrPHLuienxCJZpfEfc/xi/o56iS/4MP2KU=
